#!/bin/bash
################################################################################
# Household-wide dnsmasq blocklist (one file for all clients using this Pi DNS).
#
# Reads domains from stdin (same format as update_dnsmasq_blocklist.sh):
#   DOMAIN:BLOCK_SUBDOMAINS  (1 = block subdomains, 0 = apex only)
#
# Writes: /etc/dnsmasq.d/parental-global-blocklist.conf
# Removes legacy per-MAC files: /etc/dnsmasq.d/blocked-domains-*.conf
#   (those never scoped DNS per client; removing avoids duplicate rules.)
#
# Usage: echo "facebook.com:1" | ./update_dnsmasq_global_blocklist.sh
################################################################################
set -e
set -u

if [ $# -ne 0 ]; then
    echo "Usage: $0 < stdin" >&2
    echo "Stdin format: DOMAIN:BLOCK_SUBDOMAINS (one per line)" >&2
    exit 1
fi

DNSMASQ_DIR="/etc/dnsmasq.d"
CONFIG_FILE="${DNSMASQ_DIR}/parental-global-blocklist.conf"

if [ ! -d "$DNSMASQ_DIR" ]; then
    echo "Error: dnsmasq.d directory does not exist: $DNSMASQ_DIR" >&2
    exit 2
fi

TEMP_CONFIG=$(mktemp)
trap "rm -f $TEMP_CONFIG" EXIT

cat > "$TEMP_CONFIG" <<EOF
# Global blocked domains (all child devices / household policy)
# Generated by update_dnsmasq_global_blocklist.sh
# Auto-generated - do not edit manually
# Last updated: $(date)

EOF

DOMAIN_COUNT=0
while IFS= read -r line || [ -n "$line" ]; do
    if [ -z "$line" ] || [[ "$line" =~ ^# ]]; then
        continue
    fi
    DOMAIN=$(echo "$line" | cut -d':' -f1)
    BLOCK_SUBDOMAINS=$(echo "$line" | cut -d':' -f2)
    if [ -z "$DOMAIN" ]; then
        continue
    fi
    if [ "$BLOCK_SUBDOMAINS" = "1" ]; then
        echo "address=/.${DOMAIN}/127.0.0.1" >> "$TEMP_CONFIG"
    else
        echo "address=/${DOMAIN}/127.0.0.1" >> "$TEMP_CONFIG"
    fi
    DOMAIN_COUNT=$((DOMAIN_COUNT + 1))
done

FILE_REMOVED=0

if [ $DOMAIN_COUNT -eq 0 ]; then
    if [ -f "$CONFIG_FILE" ]; then
        sudo rm "$CONFIG_FILE"
        FILE_REMOVED=1
        echo "Removed global blocklist (no domains to block)"
    else
        echo "No domains to block (global list empty)"
    fi
else
    sudo mv "$TEMP_CONFIG" "$CONFIG_FILE"
    sudo chmod 644 "$CONFIG_FILE"
    echo "Generated global blocklist with $DOMAIN_COUNT domain rule(s)"
fi

# Drop legacy per-MAC configs written by update_dnsmasq_blocklist.sh
shopt -s nullglob
for f in "${DNSMASQ_DIR}"/blocked-domains-*.conf; do
    sudo rm -f "$f"
    echo "Removed legacy blocklist: $f"
done
shopt -u nullglob

restart_dnsmasq() {
    if systemctl is-failed --quiet dnsmasq 2>/dev/null; then
        echo "Resetting dnsmasq start-limit..." >&2
        sudo systemctl reset-failed dnsmasq 2>/dev/null || true
        sleep 1
    fi
    sleep 2
    if sudo systemctl restart dnsmasq 2>/dev/null; then
        return 0
    fi
    return 1
}

MAX_RETRIES=3
RETRY_DELAY=2
RESTART_SUCCESS=0
for i in $(seq 1 $MAX_RETRIES); do
    if restart_dnsmasq; then
        RESTART_SUCCESS=1
        break
    fi
    if [ $i -eq $MAX_RETRIES ]; then
        if [ $FILE_REMOVED -eq 1 ]; then
            echo "Warning: dnsmasq restart failed after $MAX_RETRIES attempts; global blocklist file was removed" >&2
            exit 0
        fi
        echo "Error: Failed to restart dnsmasq after $MAX_RETRIES attempts" >&2
        exit 2
    fi
    echo "Retrying dnsmasq restart (attempt $i/$MAX_RETRIES)..." >&2
    sleep $RETRY_DELAY
    RETRY_DELAY=$((RETRY_DELAY * 2))
done

if [ $RESTART_SUCCESS -eq 1 ]; then
    sleep 1
    if ! systemctl is-active --quiet dnsmasq; then
        if [ $FILE_REMOVED -eq 1 ]; then
            exit 0
        fi
        echo "Error: dnsmasq is not active after restart" >&2
        exit 2
    fi
fi

echo "Successfully updated global dnsmasq blocklist"
exit 0
