#!/bin/bash

################################################################################
# Update dnsmasq Blocklist Script
# 
# Purpose: Regenerate the complete dnsmasq blocklist for a device from
#          the database. This ensures the dnsmasq config matches the database state.
#
# Usage:   ./update_dnsmasq_blocklist.sh <MAC_ADDRESS>
# Example: ./update_dnsmasq_blocklist.sh AA:BB:CC:DD:EE:FF
#
# What This Script Does:
# 1. Validates the MAC address format
# 2. Normalizes MAC address to standard format (with colons)
# 3. Reads blocked domains from database (via Laravel command or JSON file)
# 4. Generates complete dnsmasq config file with all domains
# 5. Handles subdomain blocking (wildcard patterns)
# 6. Restarts dnsmasq service to apply changes
# 7. Returns exit code 0 on success, non-zero on error
#
# Exit Codes:
#   0 = Success (blocklist updated)
#   1 = Validation error (invalid MAC address format)
#   2 = dnsmasq error (failed to generate config or restart service)
#
# Important Notes:
# - This script requires sudo privileges for dnsmasq operations
# - The script is idempotent (safe to run multiple times)
# - Regenerates config from scratch (ensures consistency with database)
# - Handles bulk updates, deletions, and complex scenarios
#
# Why This Script?
# - Database is the source of truth for blocked domains
# - dnsmasq config can get out of sync (manual edits, script failures, etc.)
# - This script ensures consistency by regenerating config from database
# - Called after creating/updating/deleting blocked websites
#
# Input Format:
# - Reads domains from stdin (one domain per line)
# - Format: DOMAIN:BLOCK_SUBDOMAINS
# - Example: facebook.com:1 (blocks facebook.com and *.facebook.com)
# - Example: api.facebook.com:0 (blocks only api.facebook.com)
#
# dnsmasq Config Format:
# - address=/domain.com/127.0.0.1 (blocks main domain)
# - address=/.domain.com/127.0.0.1 (blocks domain and all subdomains)
################################################################################

# Set script to exit immediately if any command fails
# This prevents the script from continuing after an error
set -e

# Set script to exit if any variable is used before being set
# This prevents bugs from uninitialized variables
set -u

################################################################################
# Function: validate_mac_address
# 
# Purpose: Check if the MAC address is in a valid format
#
# Input:   MAC address string (e.g., "AA:BB:CC:DD:EE:FF" or "AA-BB-CC-DD-EE-FF")
# Output:  Returns 0 if valid, 1 if invalid
################################################################################
validate_mac_address() {
    local mac="$1"
    
    if [ -z "$mac" ]; then
        echo "Error: MAC address cannot be empty" >&2
        return 1
    fi
    
    if ! echo "$mac" | grep -qE '^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$'; then
        echo "Error: Invalid MAC address format: $mac" >&2
        return 1
    fi
    
    return 0
}

################################################################################
# Function: normalize_mac_address
# 
# Purpose: Normalize MAC address to standard format (with colons)
#
# Input:   MAC address string (any format)
# Output:  Normalized MAC address (XX:XX:XX:XX:XX:XX)
################################################################################
normalize_mac_address() {
    local mac="$1"
    mac=$(echo "$mac" | tr '-' ':')
    mac=$(echo "$mac" | tr '[:lower:]' '[:upper:]')
    echo "$mac"
}

################################################################################
# Main Script Logic
################################################################################

# Check if correct number of arguments provided
if [ $# -ne 1 ]; then
    echo "Usage: $0 <MAC_ADDRESS>" >&2
    echo "Example: $0 AA:BB:CC:DD:EE:FF" >&2
    echo "" >&2
    echo "This script reads blocked domains from stdin." >&2
    echo "Format: DOMAIN:BLOCK_SUBDOMAINS (one per line)" >&2
    echo "Example: facebook.com:1" >&2
    echo "Example: api.facebook.com:0" >&2
    exit 1
fi

# Get arguments
MAC_ADDRESS="$1"

# Validate MAC address
if ! validate_mac_address "$MAC_ADDRESS"; then
    exit 1
fi

# Normalize MAC address
NORMALIZED_MAC=$(normalize_mac_address "$MAC_ADDRESS")

# dnsmasq config directory
DNSMASQ_DIR="/etc/dnsmasq.d"
CONFIG_FILE="${DNSMASQ_DIR}/blocked-domains-${NORMALIZED_MAC}.conf"

# Ensure dnsmasq.d directory exists
if [ ! -d "$DNSMASQ_DIR" ]; then
    echo "Error: dnsmasq.d directory does not exist: $DNSMASQ_DIR" >&2
    exit 2
fi

# Create temporary config file
TEMP_CONFIG=$(mktemp)
trap "rm -f $TEMP_CONFIG" EXIT

# Write header to config file
cat > "$TEMP_CONFIG" <<EOF
# Blocked domains for device ${NORMALIZED_MAC}
# Generated by update_dnsmasq_blocklist.sh
# Auto-generated - do not edit manually
# Last updated: $(date)

EOF

# Read domains from stdin and add to config
# Format: DOMAIN:BLOCK_SUBDOMAINS
# Example: facebook.com:1 (blocks facebook.com and *.facebook.com)
# Example: api.facebook.com:0 (blocks only api.facebook.com)
DOMAIN_COUNT=0
while IFS= read -r line || [ -n "$line" ]; do
    # Skip empty lines and comments
    if [ -z "$line" ] || [[ "$line" =~ ^# ]]; then
        continue
    fi
    
    # Parse domain and block_subdomains flag
    DOMAIN=$(echo "$line" | cut -d':' -f1)
    BLOCK_SUBDOMAINS=$(echo "$line" | cut -d':' -f2)
    
    # Validate domain format (basic check)
    if [ -z "$DOMAIN" ]; then
        continue
    fi
    
    # Add domain to config
    if [ "$BLOCK_SUBDOMAINS" = "1" ]; then
        # Block subdomains (wildcard pattern)
        echo "address=/.${DOMAIN}/127.0.0.1" >> "$TEMP_CONFIG"
    else
        # Block only main domain
        echo "address=/${DOMAIN}/127.0.0.1" >> "$TEMP_CONFIG"
    fi
    
    DOMAIN_COUNT=$((DOMAIN_COUNT + 1))
done

# If no domains, create empty file (or remove existing)
if [ $DOMAIN_COUNT -eq 0 ]; then
    if [ -f "$CONFIG_FILE" ]; then
        sudo rm "$CONFIG_FILE"
        echo "Removed blocklist file for device ${NORMALIZED_MAC} (no domains to block)"
    else
        echo "No domains to block for device ${NORMALIZED_MAC}"
    fi
else
    # Move temporary config to final location
    sudo mv "$TEMP_CONFIG" "$CONFIG_FILE"
    sudo chmod 644 "$CONFIG_FILE"
    echo "Generated blocklist with $DOMAIN_COUNT domain(s) for device ${NORMALIZED_MAC}"
fi

# Restart dnsmasq service to apply changes
if ! sudo systemctl restart dnsmasq; then
    echo "Error: Failed to restart dnsmasq service" >&2
    exit 2
fi

# Verify dnsmasq is running
if ! systemctl is-active --quiet dnsmasq; then
    echo "Error: dnsmasq service is not running after restart" >&2
    exit 2
fi

echo "Successfully updated dnsmasq blocklist for device ${NORMALIZED_MAC}"
exit 0

