#!/bin/bash
################################################################################
# DHCP DNS bypass for parent/guest/whitelisted MACs (split DNS vs household blocklist).
#
# dnsmasq global `address=` rules apply to every client that uses this resolver.
# Devices that must NOT use Pi DNS get DHCP option 6 set to upstream resolvers.
#
# Usage:
#   printf '%s\n' "aa:bb:cc:dd:ee:ff" | ./update_dnsmasq_dhcp_dns_bypass.sh 8.8.8.8 1.1.1.1
#
# Args:
#   $1 Primary DNS (IPv4)
#   $2 Secondary DNS (IPv4)
# Stdin:
#   One MAC address per line (colons, any case). Invalid lines skipped.
#
# Writes: /etc/dnsmasq.d/parental-dhcp-dns-bypass.conf
################################################################################
set -euo pipefail

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <primary_dns_ipv4> <secondary_dns_ipv4> < stdin (one MAC per line)" >&2
    exit 1
fi

DNS_PRIMARY="$1"
DNS_SECONDARY="$2"

if ! [[ "$DNS_PRIMARY" =~ ^[0-9]{1,3}(\.[0-9]{1,3}){3}$ ]] || ! [[ "$DNS_SECONDARY" =~ ^[0-9]{1,3}(\.[0-9]{1,3}){3}$ ]]; then
    echo "Error: DNS arguments must be IPv4 addresses" >&2
    exit 1
fi

DNSMASQ_DIR="/etc/dnsmasq.d"
CONFIG_FILE="${DNSMASQ_DIR}/parental-dhcp-dns-bypass.conf"

if [ ! -d "$DNSMASQ_DIR" ]; then
    echo "Error: dnsmasq.d directory does not exist: $DNSMASQ_DIR" >&2
    exit 2
fi

MAC_REGEX='^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$'

TEMP_CONFIG=$(mktemp)
trap 'rm -f "$TEMP_CONFIG"' EXIT

cat > "$TEMP_CONFIG" <<EOF
# MAC-tagged DHCP DNS bypass (parent/guest/whitelisted — not subject to Pi dnsmasq blocklist)
# Generated by update_dnsmasq_dhcp_dns_bypass.sh
# Auto-generated - do not edit manually
# Last updated: $(date)

EOF

MAC_COUNT=0
declare -A SEEN_MACS

while IFS= read -r line || [ -n "$line" ]; do
    line="${line//$'\r'/}"
    line="${line#"${line%%[![:space:]]*}"}"
    line="${line%"${line##*[![:space:]]}"}"
    if [ -z "$line" ] || [[ "$line" =~ ^# ]]; then
        continue
    fi
    mac=$(printf '%s' "$line" | tr '[:upper:]' '[:lower:]')
    if ! [[ "$mac" =~ $MAC_REGEX ]]; then
        echo "Warning: skipping invalid MAC line: $line" >&2
        continue
    fi
    if [[ -n "${SEEN_MACS[$mac]:-}" ]]; then
        continue
    fi
    SEEN_MACS[$mac]=1
    echo "dhcp-mac=set:dnsBypass,${mac}" >> "$TEMP_CONFIG"
    MAC_COUNT=$((MAC_COUNT + 1))
done

if [ "$MAC_COUNT" -gt 0 ]; then
    echo "dhcp-option-force=tag:dnsBypass,option:dns-server,${DNS_PRIMARY},${DNS_SECONDARY}" >> "$TEMP_CONFIG"
fi

FILE_REMOVED=0

if [ "$MAC_COUNT" -eq 0 ]; then
    if [ -f "$CONFIG_FILE" ]; then
        sudo rm -f "$CONFIG_FILE"
        FILE_REMOVED=1
        echo "Removed DHCP DNS bypass config (no MACs to bypass)"
    else
        echo "No bypass MACs (config absent or already empty)"
    fi
else
    sudo mv "$TEMP_CONFIG" "$CONFIG_FILE"
    sudo chmod 644 "$CONFIG_FILE"
    echo "Generated DHCP DNS bypass for $MAC_COUNT MAC(s) -> ${DNS_PRIMARY}, ${DNS_SECONDARY}"
fi

restart_dnsmasq() {
    if systemctl is-failed --quiet dnsmasq 2>/dev/null; then
        echo "Resetting dnsmasq start-limit..." >&2
        sudo systemctl reset-failed dnsmasq 2>/dev/null || true
        sleep 1
    fi
    sleep 2
    if sudo systemctl restart dnsmasq 2>/dev/null; then
        return 0
    fi
    return 1
}

MAX_RETRIES=3
RETRY_DELAY=2
RESTART_SUCCESS=0
for i in $(seq 1 $MAX_RETRIES); do
    if restart_dnsmasq; then
        RESTART_SUCCESS=1
        break
    fi
    if [ "$i" -eq $MAX_RETRIES ]; then
        if [ "$FILE_REMOVED" -eq 1 ]; then
            echo "Warning: dnsmasq restart failed after $MAX_RETRIES attempts; bypass file was removed" >&2
            exit 0
        fi
        echo "Error: Failed to restart dnsmasq after $MAX_RETRIES attempts" >&2
        exit 2
    fi
    echo "Retrying dnsmasq restart (attempt $i/$MAX_RETRIES)..." >&2
    sleep "$RETRY_DELAY"
    RETRY_DELAY=$((RETRY_DELAY * 2))
done

if [ "$RESTART_SUCCESS" -eq 1 ]; then
    sleep 1
    if ! systemctl is-active --quiet dnsmasq; then
        if [ "$FILE_REMOVED" -eq 1 ]; then
            exit 0
        fi
        echo "Error: dnsmasq is not active after restart" >&2
        exit 2
    fi
fi

echo "Successfully updated dnsmasq DHCP DNS bypass config"
exit 0
