<?php

namespace App\Http\Controllers;

use App\Models\AccessAttempt;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\View\View;

/**
 * Access Attempt Controller
 * 
 * This controller handles viewing security events (access attempts) for child devices.
 * Access attempts are automatically created by the system when:
 * 1. A child tries to access a blocked website (type: 'blocked_website')
 * 2. A child visits a flagged website (type: 'flagged_website')
 * 
 * What is an Access Attempt?
 * - An access attempt is a security event that occurs when a child device interacts
 *   with a blocked or flagged website
 * - There are two types:
 *   1. Blocked Website Attempt: Child tried to access a blocked site (access denied)
 *      - The system blocks the request and logs the attempt
 *      - Parent is notified that child tried to access a blocked site
 *   2. Flagged Website Visit: Child visited a flagged site (access allowed but logged)
 *      - The system allows access but logs the visit
 *      - Parent is notified that child visited a flagged site
 * 
 * Why Do We Track Access Attempts?
 * - Security: Parents need to know when children try to access blocked sites
 * - Monitoring: Parents can see which flagged sites children are visiting
 * - Compliance: Helps parents ensure children follow internet usage rules
 * - Alerts: Triggers real-time notifications to parents
 * 
 * Key Responsibilities:
 * 1. List access attempts with filtering (device, type, date range, search)
 * 2. Ensure parents can only view attempts for their own devices (authorization)
 * 3. Provide pagination for large result sets
 * 
 * Authorization:
 * - All methods require authentication (user must be logged in)
 * - AccessAttemptPolicy ensures users can only view attempts for their own devices
 * - Uses $this->authorize() to check permissions before operations
 * 
 * Data Flow:
 * 1. Child device tries to access blocked/flagged website
 * 2. System creates AccessAttempt record in database
 * 3. Parent visits /access-attempts page
 * 4. Controller filters attempts by device ownership
 * 5. Returns filtered, paginated results to view
 */
class AccessAttemptController extends Controller
{
    /**
     * AuthorizesRequests trait provides the authorize() method for policy checks.
     * This allows us to use $this->authorize() in controller methods.
     */
    use AuthorizesRequests;

    /**
     * Display a listing of access attempts.
     * 
     * Route: GET /access-attempts
     * 
     * Shows all access attempts for the authenticated user's devices.
     * Filterable by device, type, date range, and search term.
     * 
     * Query Parameters:
     * - device_id: Filter by specific device (optional, can be pre-filled from Child Devices page)
     * - type: Filter by attempt type (optional: 'blocked_website' or 'flagged_website')
     * - from_date: Start date for date range filter (optional, format: Y-m-d)
     * - to_date: End date for date range filter (optional, format: Y-m-d)
     * - search: Search term for domain/URL (optional)
     * 
     * How Filtering Works:
     * 1. Device Filter: Shows only attempts for selected device (if device_id provided)
     * 2. Type Filter: Shows only blocked or flagged attempts (if type provided)
     * 3. Date Range Filter: Shows only attempts within the specified date range
     * 4. Search Filter: Searches in both domain and URL fields using LIKE query
     * 5. All filters can be combined (e.g., device + type + date range + search)
     * 
     * Pagination:
     * - Results are paginated (20 per page) to handle large datasets
     * - Pagination links are automatically generated by Laravel
     * - Each page shows 20 access attempt records
     * 
     * Performance:
     * - Uses eager loading (->with('device')) to avoid N+1 queries
     * - Uses whereHas() to filter by device ownership efficiently
     * - Database indexes on device_id, type, and attempted_at ensure fast queries
     * 
     * @param Request $request HTTP request (may contain filter parameters)
     * @return View The access attempts index view
     */
    public function index(Request $request): View
    {
        // Check authorization: Can the user view access attempts?
        // This calls AccessAttemptPolicy@viewAny() to check permissions
        $this->authorize('viewAny', AccessAttempt::class);

        // Get all devices for the authenticated user
        // This is used to populate the device filter dropdown
        $devices = Auth::user()->devices()->orderBy('name')->get();

        // Build query for access attempts
        // whereHas('device') ensures we only get attempts for devices owned by the user
        // This is a security measure: parents can only see attempts for their own devices
        $query = AccessAttempt::whereHas('device', function ($q) {
            // Filter devices by user_id to ensure user only sees their own devices' attempts
            $q->where('user_id', Auth::id());
        })->with('device'); // Eager load device relationship to avoid N+1 queries

        // Filter by device if provided
        // This allows filtering to a specific device (e.g., from Child Devices page)
        if ($request->filled('device_id')) {
            // Validate that the device belongs to the user (security check)
            $device = Auth::user()->devices()->find($request->device_id);
            if ($device) {
                $query->where('device_id', $request->device_id);
            }
        }

        // Filter by type if provided
        // This allows filtering to blocked_website or flagged_website attempts
        if ($request->filled('type')) {
            // Validate that the type is one of the allowed values
            $allowedTypes = ['blocked_website', 'flagged_website'];
            if (in_array($request->type, $allowedTypes)) {
                $query->where('type', $request->type);
            }
        }

        // Filter by date range if provided
        // This allows parents to view attempts for a specific time period
        if ($request->filled('from_date')) {
            // Parse the date string and filter attempts on or after this date
            $query->whereDate('attempted_at', '>=', $request->from_date);
        }

        if ($request->filled('to_date')) {
            // Parse the date string and filter attempts on or before this date
            $query->whereDate('attempted_at', '<=', $request->to_date);
        }

        // Search by domain/URL if provided
        // This allows parents to search for specific websites
        if ($request->filled('search')) {
            $search = $request->search;
            // Search in both domain and URL fields using LIKE query
            // %{$search}% means "contains search term" (case-insensitive)
            $query->where(function ($q) use ($search) {
                $q->where('domain', 'like', "%{$search}%")
                  ->orWhere('url', 'like', "%{$search}%");
            });
        }

        // Order by attempted_at DESC (newest first)
        // This shows the most recent security events first
        // Paginate results (20 per page) to handle large datasets efficiently
        $accessAttempts = $query->orderBy('attempted_at', 'desc')->paginate(20);

        // Pass data to the view
        // compact() creates an array with variables: ['accessAttempts' => $accessAttempts, 'devices' => $devices]
        return view('access-attempts.index', compact('accessAttempts', 'devices'));
    }
}

