<?php

namespace App\Http\Controllers;

use App\Models\BrowsingLog;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\View\View;

/**
 * Browsing Log Controller
 * 
 * This controller handles viewing browsing history for child devices.
 * Browsing logs are automatically created by the ParseNetworkLogs background job,
 * which parses network traffic logs and stores website visits in the database.
 * 
 * What is a Browsing Log?
 * - A browsing log is a record of every website a child device visits
 * - It contains: URL, domain, timestamp, bandwidth usage, and device information
 * - Logs are created automatically by the ParseNetworkLogs job (runs every 10 minutes)
 * - Parents can view these logs to monitor their children's internet activity
 * 
 * Key Responsibilities:
 * 1. List browsing logs with filtering (device, date range, search)
 * 2. Ensure parents can only view logs for their own devices (authorization)
 * 3. Provide pagination for large result sets
 * 
 * Authorization:
 * - All methods require authentication (user must be logged in)
 * - BrowsingLogPolicy ensures users can only view logs for their own devices
 * - Uses $this->authorize() to check permissions before operations
 * 
 * Data Flow:
 * 1. ParseNetworkLogs job parses network traffic logs
 * 2. Creates BrowsingLog records in database
 * 3. Parent visits /browsing-logs page
 * 4. Controller filters logs by device ownership
 * 5. Returns filtered, paginated results to view
 */
class BrowsingLogController extends Controller
{
    /**
     * AuthorizesRequests trait provides the authorize() method for policy checks.
     * This allows us to use $this->authorize() in controller methods.
     */
    use AuthorizesRequests;

    /**
     * Display a listing of browsing logs.
     * 
     * Route: GET /browsing-logs
     * 
     * Shows all browsing logs for the authenticated user's devices.
     * Filterable by device, date range, and search term.
     * 
     * Query Parameters:
     * - device_id: Filter by specific device (optional, can be pre-filled from Child Devices page)
     * - from_date: Start date for date range filter (optional, format: Y-m-d)
     * - to_date: End date for date range filter (optional, format: Y-m-d)
     * - search: Search term for domain/URL (optional)
     * 
     * How Filtering Works:
     * 1. Device Filter: Shows only logs for selected device (if device_id provided)
     * 2. Date Range Filter: Shows only logs within the specified date range
     * 3. Search Filter: Searches in both domain and URL fields using LIKE query
     * 4. All filters can be combined (e.g., device + date range + search)
     * 
     * Pagination:
     * - Results are paginated (20 per page) to handle large datasets
     * - Pagination links are automatically generated by Laravel
     * - Each page shows 20 browsing log records
     * 
     * Performance:
     * - Uses eager loading (->with('device')) to avoid N+1 queries
     * - Uses whereHas() to filter by device ownership efficiently
     * - Database indexes on device_id and visited_at ensure fast queries
     * 
     * @param Request $request HTTP request (may contain filter parameters)
     * @return View The browsing logs index view
     */
    public function index(Request $request): View
    {
        // Check authorization: Can the user view browsing logs?
        // This calls BrowsingLogPolicy@viewAny() to check permissions
        $this->authorize('viewAny', BrowsingLog::class);

        // Get all devices for the authenticated user
        // This is used to populate the device filter dropdown
        $devices = Auth::user()->devices()->orderBy('name')->get();

        // Build query for browsing logs
        // whereHas('device') ensures we only get logs for devices owned by the user
        // This is a security measure: parents can only see logs for their own devices
        $query = BrowsingLog::whereHas('device', function ($q) {
            // Filter devices by user_id to ensure user only sees their own devices' logs
            $q->where('user_id', Auth::id());
        })->with('device'); // Eager load device relationship to avoid N+1 queries

        // Filter by device if provided
        // This allows filtering to a specific device (e.g., from Child Devices page)
        if ($request->filled('device_id')) {
            // Validate that the device belongs to the user (security check)
            $device = Auth::user()->devices()->find($request->device_id);
            if ($device) {
                $query->where('device_id', $request->device_id);
            }
        }

        // Filter by date range if provided
        // This allows parents to view logs for a specific time period
        if ($request->filled('from_date')) {
            // Parse the date string and filter logs visited on or after this date
            $query->whereDate('visited_at', '>=', $request->from_date);
        }

        if ($request->filled('to_date')) {
            // Parse the date string and filter logs visited on or before this date
            $query->whereDate('visited_at', '<=', $request->to_date);
        }

        // Search by domain/URL if provided
        // This allows parents to search for specific websites
        if ($request->filled('search')) {
            $search = $request->search;
            // Search in both domain and URL fields using LIKE query
            // %{$search}% means "contains search term" (case-insensitive)
            $query->where(function ($q) use ($search) {
                $q->where('domain', 'like', "%{$search}%")
                  ->orWhere('url', 'like', "%{$search}%");
            });
        }

        // Order by visited_at DESC (newest first)
        // This shows the most recent browsing activity first
        // Paginate results (20 per page) to handle large datasets efficiently
        $browsingLogs = $query->orderBy('visited_at', 'desc')->paginate(20);

        // Pass data to the view
        // compact() creates an array with variables: ['browsingLogs' => $browsingLogs, 'devices' => $devices]
        return view('browsing-logs.index', compact('browsingLogs', 'devices'));
    }
}

